config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'users/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  post 'addbook' => 'books_controller#addbook' 
  get 'addbook' => 'books#addbook' 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :books, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user if logged_in?
    @books = Book.paginate(page: params[:page])
    
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="center jumbotron">
<h1>Contact</h1>
    <p>
      Contact the Ruby on Rails Tutorial about the sample app at the
      <a href="http://www.railstutorial.org/#contact">contact page</a>.
    </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<%= image_tag("TEXTCHANGE.png", :class => "header_img") %>
<div class="center jumbotron">
<h1>Help</h1>

</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<%= image_tag("TEXTCHANGE.png", :class => "header_img") %>
<div class="center jumbotron">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <% @books.each do |booka| %>
      <% if booka.user_id == @user.id && booka.bookstatus == 'wanted' %>
        <% @books.each do |bookb| %>
          <% if bookb.bookstatus == 'owned' && bookb.isbn == booka.isbn %>
            <% @books.each do |bookc| %>
              <% if bookc.user_id == bookb.user_id && bookc.bookstatus == 'wanted' %>
                <% @books.each do |bookd| %>
                  <% if bookd.bookstatus == 'owned' && bookd.isbn == bookc.isbn && bookd.user_id == @user.id%>
                    <li>
                      <bk1>
                      <%= booka.title %>
                      <%= booka.bookstatus %>
                      <%= bookb.title %>
                      <%= bookb.bookstatus %>
                      </bk1>
                      
                      <bk2>
                      <%= bookc.title %>
                      <%= bookc.bookstatus %>
                      <%= bookd.title %>
                      <%= bookd.bookstatus %>
                      </bk2>
                    </li>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

</div>
<% else %>
<%= image_tag("TEXTCHANGE.png", :class => "header_img") %>

<div class="center jumbotron">
  
  <h3>
    Swap textbooks for free
  </h3>
  
  <hand>
    <%= image_tag"handShake.png"%>
  </hand>

  <h2>
    A place to borrow and lend text books, to save you money and recycle books!
    Get in contact with people who have a book you need this semester, hopefully you've got what they want!
  </h2>
  
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
  

  
</div>
<% end %>